model_path:
  small: "./models/capybarahermes-2.5-mistral-7b.Q2_K.gguf"
  large:  "./models/capybarahermes-2.5-mistral-7b.Q2_K.gguf"

model_type: "mistral"

embeddings_path: "BAAI/bge-large-en-v1.5"